language: android

sudo : false

jdk: openjdk8

env:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
  licenses:
    - ".+"

branches:
  only:
    - master

script:
  - ./gradlew assemble$BUILD_TYPE check$BUILD_TYPE

notifications:
  email: false

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle"

before_install:
 - yes | sdkmanager "ndk-bundle"
