language: android

jdk:
- openjdk8
- oraclejdk8

android:
  components:
    - tools
    - build-tools-28.0.2
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - ".+"

script:
  - "./gradlew clean assembleDebug"

notifications:
  email: false

sudo: false

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$ANDROID_HOME"

before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "ndk-bundle"
