language: android

sudo : false

addons:
  apt:
    packages:
      - aria2

jdk: openjdk8

android:
  components:
    - tools
    - build-tools-28.0.2
    - android-28
    - extra-android-m2repository
  licenses:
    - ".+"

branches:
  only:
    - master

script:
  - source ci/style-check.sh
  - "./gradlew :app:assembleDebug :app:lint"
  - bash ci/notify-test.sh

notifications:
  email: false

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.gradle"

before_install:
 - yes | sdkmanager "ndk-bundle"