name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:

    - name: Checkout repository and submodules
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Install go compiler for libwg-go
      uses: actions/setup-go@v1
      with:
        go-version: '1.13.4'

    - name: Clean Cache
      run: rm -rf ~/.gradle/caches

    - uses: actions/cache@v1
      with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/dependencies.gradle') }}

    - name: Decrypt secrets
      run: release/signing-setup.sh "$ENCRYPT_KEY"
      env:
        ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

    - name: Download gradle dependencies
      run: ./gradlew dependencies

    - name: Validate codestyle with Spotless
      run: ./gradlew spotlessCheck

    - name: Build app
      run: ./gradlew :app:assembleDebug

    - name: Clean secrets
      run: release/signing-cleanup.sh

    - name: Deploy to Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        document: app/build/outputs/apk/debug/app-debug.apk

    - name: Archive debug APK
      uses: actions/upload-artifact@master
      with:
        name: Viscerion-debug
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Run unit tests
      run: ./gradlew testDebug
