name: "CI builds"
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Install coreutils
      run: brew install coreutils
    - name: Install Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.0.3
    - name: Checkout repository and submodules
      uses: actions/checkout@master
      with:
        submodules: true
    - name: Install go compiler for libwg-go
      uses: actions/setup-go@v1
      with:
        go-version: '1.13.4'
    - name: Download gradle dependencies
      run: ./gradlew dependencies
    - name: Validate codestyle with Spotless
      run: ./gradlew spotlessCheck
    - name: Build app
      run: ./gradlew :app:assembleDebug
    - name: Run instrumentation tests
      uses: malinskiy/action-android/emulator-run-cmd@release/0.0.3
      with:
        cmd: ./gradlew connectedCheck --stacktrace
        api: 21
        tag: default
        abi: x86
    - uses: actions/upload-artifact@master
      with:
        name: viscerion-${{ github.sha }}
        path: app/build/outputs/apk/debug/app-debug.apk
