name: "CI builds"
on: [push, pull_request]

jobs:
  setup-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: Cache ~/.gradle
      uses: actions/cache@preview
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/.gradle/workspace-id.txt') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.3'
    - run: ./gradlew dependencies spotlessCheck :app:assembleDebug
    - uses: actions/upload-artifact@master
      with:
        name: Debug APK
        path: app/build/outputs/apk/debug/app-debug.apk
